language: node_js
node_js:
- '6'
- '5'
- '4'
deploy:
  provider: npm
  email: stefano+npm@sala.io
  api_key:
    secure: iF2+UizQwSFTUahEtkCOFWGZgvgZ+hxxunqfu2CX50le+Hy0s8z+NnrdADPPohWxnnuU8TQO2QFN71nroek0TY9CC+nAYccyu3bnMdO1v9RWlikegGGeDYcmakAphxN7aO77QmN3FWfXRMblOc+XTzm+kiO+nhw9hbOG52ZOprc=
  on:
    tags: true
    repo: antecons/antecons-node
notifications:
  slack:
    secure: bop7SIc1IrvE+NLB4EvFGkFm1FNS00mB5Tnz45hcn6X9wvFTe5cdZ4bKjH1nWambfFDl/ozjH1ZjrUiy46+dIad8D41wUuepErgCOeOUnCbq4W7hFAbMSKZgcda6Xs+lFIr3NnCE+PPCb3ijx8XQsYJ+fp1Xfun11xjF6PNSI10=
